services:
  almalinux10_snmp_container:
    build:
      context: ../../
      dockerfile: docker/almalinux10/Dockerfile
    container_name: almalinux10_snmp_container
    volumes:
      - ../../:/ezsnmp
    working_dir: /ezsnmp
    entrypoint: ["/usr/local/bin/DockerEntry.sh"]
