services:
  archlinux_netsnmp_5.8_snmp_container:
    build:
      context: ../../
      dockerfile: docker/archlinux_netsnmp_5.8/Dockerfile
    container_name: archlinux_netsnmp_5.8_snmp_container
    volumes:
      - ../../:/ezsnmp
    working_dir: /ezsnmp
    entrypoint: ["/ezsnmp/docker/archlinux_netsnmp_5.8/DockerEntry.sh"]
