services:
  rockylinux9_snmp_container:
    build:
      context: ../../
      dockerfile: docker/rockylinux9_netsnmp_5.9/Dockerfile
    container_name: rockylinux9_snmp_container
    volumes:
      - ../../:/ezsnmp
    working_dir: /ezsnmp
    entrypoint: ["/usr/local/bin/DockerEntry.sh"]

