style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/carlkidcrypto/ezsnmp
options:
  commits:
    # filters:
    #   Type:
    #     - feat
    #     - fix
    #     - perf
    #     - refactor
  commit_groups:
    title_maps:
      # Lowercase conventional commits
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      docs: Documentation Updates
      chore: Maintenance
      build: Build System
      ci: Continuous Integration
      test: Tests
      style: Styles
      revert: Reverts
      # Capitalized word prefixes
      Fix: Bug Fixes
      Refactor: Code Refactoring
      Bump: Dependency Updates
      Add: New Features
      Update: Updates
      Document: Documentation Updates
      Increase: Performance Improvements
      Modernize: Code Improvements
      Python: Python Changes
      Feature: Features
      Hotfix: Bug Fixes
      Enhance: Enhancements
      Use: Code Changes
      Initial: Initial Changes
      # Merge commits
      Merge: Merged Pull Requests
      # Fallback
      other: Other Changes
  header:
    pattern: "^\\s*(([\\w\\d]+)(?:[:\\s/-].*)?)$"
    pattern_maps:
      - Subject
      - Type
  notes:
    keywords:
      - BREAKING CHANGE